scil-vital/dwi_ml

.pep8speaks.yml
Add PEP8 style checker configuration file.
=> ENH: Add PEP8 style checker file configuration file

dwi_ml/data/processing/space/neighbourhood.py
arranged and tested neighbourhood vectors definition
=> neighborhood

.github/stale.yml
=> ENH: Add stale bot config file

dwi_ml/data/processing/space/neighbourhood.py
- Also changed both functions `get_neighborhood_*` to stop including `[0,0,0]` origin, which should be handled by `extend_coordinates_with_neighborhood`
=> ENH: Refactored extend_coordinates_with_neighborhood

dwi_ml/data/processing/streamlines/data_augmentation.py, dwi_ml/data/processing/streamlines/utils.py
First real PR!!
function add_noise_to_streamlines.
=> Add noise to streamlines

dwi_ml/experiment/learning_utils.py, dwi_ml/experiment/memory.py, dwi_ml/experiment/monitoring.py, dwi_ml/experiment/timer.py, dwi_ml/model/trainer_abstract.py
- LossHistoryMonitor: Biggest change. I don't think we need to keep track of the count: can be found with len(...). 
Other changes:
- Compute_gradient_norm. NOTE. THERE WAS A MATH ERROR. See if it changes your work so far. Corrected.
- Early stopping monitor: simply added more description
- memory_log: ok
- Timer: simply added more description.
- IterTimer: removed.
=> Experiment utils

.github/PULL_REQUEST_TEMPLATE.md
Added a PR template to passively enforce contributing standards. Suggestions are welcome
=> ENH: Pull request template

.github/workflows/test_package.yml
Add CI through `GitHub actions`.
--
--
=> ENH: Add CI through `GitHub actions`

README.rst
Add test, package GitHub Actions status badge to `README`.
Not needed.
Everybody.
=> DOC: Add test, package GitHub Action status badge

dwi_ml/data/processing/dwi/dwi.py, dwi_ml/data/processing/space/neighbourhood.py, dwi_ml/data/processing/streamlines/data_augmentation.py
All files in the "processing" folder should now be reviewed. Please have a last "tour d'horizon" of all files in folder. Then we can remove the "checked!" comments.
@ppoulin91 @AntoineTheb
=> Removing Checked! marks in preprocessing functions

please_copy_and_adapt/organize_from_recobundles.sh
Bash script to create symlinks to reorganize data from Recobundles.
- [x ] Added a description of the content of this PR above
- [x ] Followed [proper commit message formatting](https://chris.beams.io/posts/git-commit/)
- [x ] Tested the code yourself right before pushing
=> Reorganize recobundles

dwi_ml/data/dataset/multi_subject_containers.py, dwi_ml/data/dataset/streamline_containers.py, dwi_ml/data/dataset/subjects_list_containers.py, dwi_ml/data/hdf5_creation.py, dwi_ml/data/processing/streamlines/data_augmentation.py, dwi_ml/experiment/checks_for_experiment_parameters.py, dwi_ml/model/batch_samplers.py, please_copy_and_adapt/training_parameters.yaml, scripts_python/create_hdf5_dataset.py, tests/test_batch_sampler_iter.py, tests/test_batch_sampler_load_batch.py, tests/test_multisubjectdataset_creation_from_hdf5.py
Different use depending on compression or resampling. Chunk size is now a parameter instead of a global variable.
=> Modifying batch size, chunk size and length_mm verifications

dwi_ml/data/dataset/mri_data_containers.py, dwi_ml/data/dataset/multi_subject_containers.py, dwi_ml/data/dataset/single_subject_containers.py, dwi_ml/data/hdf5_creation.py, dwi_ml/data/processing/volume/interpolation.py, dwi_ml/experiment/batch_samplers.py, dwi_ml/models/main_models.py, scripts_python/create_hdf5_dataset.py, tests/test_batch_sampler_load_batch.py
- During training: using torch_trilinear_interpolation, which requires vox and corner
- During tracking: we will be setting voxmm and corner everywhere, as in scilpy. To prepare this, adding the resolution in the hdf5 file and in the loaded lazy/non-lazy data.
=> Clarifying spaces

dwi_ml/models/direction_getter_models.py
Cleaning direction getters in preparation for the tracking.
=> Cleaning direction getters

doc/data_containers.rst, doc/index.rst, doc/model.rst, doc/params_file.rst, doc/preprocessing.rst, doc/tracking.rst, doc/training.rst, dwi_ml/training/batch_samplers.py, dwi_ml/training/trainers.py, requirements.txt
Updating doc after last big PRs.
Note: On my newly installed computer and new python version, locally building the site (`make html`) failed because sphinx_rtd_theme is not installed by default anymore. Added to requirements.
=> Updating doc

dwi_ml/data/dataset/checks.py, dwi_ml/data/dataset/mri_data_containers.py, dwi_ml/data/dataset/multi_subject_containers.py, dwi_ml/data/dataset/single_subject_containers.py, dwi_ml/data/dataset/streamline_containers.py, dwi_ml/data/dataset/subjectdata_list_containers.py, dwi_ml/data/dataset/utils.py, please_copy_and_adapt/resume_training_from_checkpoint.py, please_copy_and_adapt/track_from_model.py, please_copy_and_adapt/train_model.py
Final proof-reading of the dataset folder before starting teams review.
=> Proof reading dataset folder

dwi_ml/training/batch_loaders.py, dwi_ml/training/batch_samplers.py, dwi_ml/training/trainers.py, dwi_ml/training/utils/batch_loaders.py, dwi_ml/training/utils/batch_sampler.py, dwi_ml/training/utils/batch_samplers.py, dwi_ml/training/utils/trainer.py, please_copy_and_adapt/resume_training_from_checkpoint.py, please_copy_and_adapt/train_model.py, tests/test_batch_sampler_iter.py, tests/test_batch_sampler_load_batch.py
Arranging batch size computation + 
Dividing batch_sampler into batch_sampler + batch_loader.
=> Batch sampler: separating dataloader and dealing better with batch size

doc/config_file.rst, doc/creating_hdf5.rst, dwi_ml/data/hdf5/hdf5_creation.py, dwi_ml/data/hdf5/utils.py, dwi_ml/data/io.py, scripts_python/dwiml_create_hdf5_dataset.py
Preparing our proof-reading PR #1 : Creating the config file + the running the hdf5 creation script.
**2 pages in the doc**
https://dwi-ml.readthedocs.io/en/latest/creating_hdf5.html
https://dwi-ml.readthedocs.io/en/latest/config_file.html
**One main code file**
hdf5_creation.py
**One utilitary file**
data/io.py
=> (Hopefully) Final PR on creating the hdf5.

dwi_ml/models/main_models.py, dwi_ml/training/trainers.py, dwi_ml/training/utils/experiment.py, dwi_ml/training/utils/trainer.py, please_copy_and_adapt/resume_training_from_checkpoint.py, please_copy_and_adapt/track_from_model.py, please_copy_and_adapt/train_model.py
Changing checkpoints to use the models' load methods.
=> Improve checkpoints

dwi_ml/data/dataset/utils.py, dwi_ml/data/processing/space/neighborhood.py, dwi_ml/models/main_models.py, dwi_ml/models/utils/direction_getters.py, dwi_ml/tests/utils.py, dwi_ml/training/utils/batch_loaders.py, dwi_ml/training/utils/batch_samplers.py, dwi_ml/training/utils/experiment.py, dwi_ml/training/utils/trainer.py, please_copy_and_adapt/dwiml_train_model.py, requirements.txt
=> Small fixes

dwi_ml/data/dataset/multi_subject_containers.py, dwi_ml/data/dataset/utils.py, dwi_ml/experiment_utils/prints.py, dwi_ml/tests/analyze_batch_loader_visually.py, dwi_ml/tests/test_batch_loader.py, dwi_ml/tests/test_batch_sampler.py, dwi_ml/tests/test_dataset.py, dwi_ml/tests/test_models_and_trainer.py, dwi_ml/training/trainers.py, dwi_ml/training/utils/experiment.py, please_copy_and_adapt/dwiml_track_from_model.py, please_copy_and_adapt/dwiml_train_model.py, please_copy_and_adapt/tests/test_all_steps.py
After talking with Phil, taskman_managed option is an old code, and better options probably exist today. Comet has not been tested in a long time, we could eventually see what's best. Removing taskman code for now.
=> Remove taskman

dwi_ml/data/dataset/multi_subject_containers.py, dwi_ml/tests/utils.py, dwi_ml/tracking/propagator.py, dwi_ml/tracking/seed.py, dwi_ml/tracking/tracker.py, dwi_ml/tracking/utils.py, please_copy_and_adapt/dwiml_track_from_model.py, please_copy_and_adapt/tests/test_all_steps.py, requirements.txt
Added the possibility to track multiple streamlines at the same time (to use on GPU).
=> Add gpu simultaneous tracking

doc/getting_started.rst, dwi_ml/data/dataset/multi_subject_containers.py, dwi_ml/data/dataset/streamline_containers.py, dwi_ml/data/hdf5/utils.py, dwi_ml/experiment_utils/prints.py, dwi_ml/experiment_utils/tqdm_logging.py, dwi_ml/models/main_models.py, dwi_ml/tests/test_dataset.py, dwi_ml/tests/test_models_and_trainer.py, dwi_ml/training/batch_loaders.py, dwi_ml/training/batch_samplers.py, dwi_ml/training/trainers.py, dwi_ml/training/utils/trainer.py, please_copy_and_adapt/tests/test_all_steps.py, requirements.txt
=> Save all experiment params

dwi_ml/data/processing/streamlines/post_processing.py, dwi_ml/models/main_models.py, dwi_ml/tracking/propagator.py, dwi_ml/tracking/tracker.py, dwi_ml/training/batch_loaders.py, dwi_ml/training/trainers.py, dwi_ml/training/utils/batch_loaders.py, dwi_ml/training/utils/experiment.py, please_copy_and_adapt/ALL_STEPS.sh, please_copy_and_adapt/config_file_example.json, please_copy_and_adapt/dwiml_resume_training_from_checkpoint.py, please_copy_and_adapt/dwiml_track_from_model.py, please_copy_and_adapt/dwiml_train_model.py
Updated ALL_STEPS.sh bash script with instructions to run everything.
=> Updated example bash script

.github/workflows/test_package.yml, dwi_ml/data/dataset/multi_subject_containers.py, dwi_ml/data/dataset/utils.py, dwi_ml/tests/test_batch_loader.py, dwi_ml/tests/test_batch_sampler.py, dwi_ml/tests/test_dataset.py, dwi_ml/tests/test_models_and_trainer.py, dwi_ml/tests/utils.py, dwi_ml/tracking/utils.py, dwi_ml/training/batch_loaders.py, dwi_ml/training/batch_samplers.py, dwi_ml/training/trainers.py, dwi_ml/training/utils/batch_loaders.py, dwi_ml/training/utils/batch_samplers.py, dwi_ml/training/utils/trainer.py, please_copy_and_adapt/dwiml_resume_training_from_checkpoint.py, please_copy_and_adapt/dwiml_train_model.py, please_copy_and_adapt/tests/test_all_steps.py, requirements.txt, requirements_github.txt
Merged the train_sampler, valid_sampler by using a context, same for the batch loader.
=> Manage train vs valid

bash_utilities/l2t_organize_from_tractoflow.sh
Small change in the case where topup was used.
Clarifying prints.
=> Add prints and add Eddy_Topup bval/bvec

dwi_ml/models/direction_getter_models.py, dwi_ml/models/projects/learn2track_model.py, dwi_ml/models/projects/transformers.py, dwi_ml/tests/unit_tests/test_losses.py, dwi_ml/tests/utils/data_and_models_for_tests.py, dwi_ml/training/trainers.py, dwi_ml/training/utils/monitoring.py, dwi_ml/training/utils/trainer.py
Loss: Mean over all batches should be weighted by the number of points in the batch.
Learning rate: argparser expected a int. Fixes.
=> Two fixes: loss and learning rate

dwi_ml/models/direction_getter_models.py
Adding a new loss:
Combined L2-regression and cosine-regression.
=> Add combined l2 + cos loss

dwi_ml/tests/unit_tests/test_models_and_trainer.py, dwi_ml/training/batch_loaders.py, dwi_ml/training/trainers.py, scripts_python/tests/scripts_on_test_model/dwiml_train_model.py, scripts_python/tests/scripts_on_test_model/test_all_steps_general.py, scripts_python/tests/test_all_steps_learn2track.py, scripts_python/tests/test_all_steps_tto.py, scripts_python/tests/test_all_steps_ttst.py
Added parameters saving as json files.
Ran into some issues during tests where files were saved in a temporary directory that didn't exist anymore. Using a more thorough temporary directory creation using pytest.
=> Add more logs and saving of parameters.

dwi_ml/data/processing/space/neighborhood.py
=> Fix radius type

dwi_ml/data/dataset/mri_data_containers.py, dwi_ml/data/dataset/multi_subject_containers.py, dwi_ml/data/processing/volume/interpolation.py, dwi_ml/models/main_models.py, dwi_ml/models/projects/learn2track_model.py, dwi_ml/models/projects/transformers.py, dwi_ml/tests/unit_tests/test_neighborhood.py, dwi_ml/tracking/projects/learn2track_propagator.py, dwi_ml/tracking/tracker.py, dwi_ml/training/projects/learn2track_trainer.py, scripts_python/l2t_resume_training_from_checkpoint.py, scripts_python/l2t_visualize_weights_evolution.py, scripts_python/tto_resume_training_from_checkpoint.py, scripts_python/ttst_resume_training_from_checkpoint.py
Add options in Learn2track to print the weights evolution through epochs.
Interpretation not straightforward but could maybe help see what's going on.
=> Visualise weights

dwi_ml/data/dataset/checks_for_groups.py, dwi_ml/data/dataset/multi_subject_containers.py, dwi_ml/data/dataset/subjectdata_list_containers.py
Small fix; count_points was using len(streamlines), which loads the streamline, instead of the variable lengths that we saved on purpuse in the hdf5, exactly for this reason.
Other changes are juste improvement in the loggers.
=> Fix counting nb points

dwi_ml/training/trainers.py
Comet was a little annoying during training.
=> Remove some comet logs

doc/model.rst, dwi_ml/models/direction_getter_models.py, dwi_ml/models/main_models.py, dwi_ml/models/projects/learn2track_model.py, dwi_ml/tests/utils/data_and_models_for_tests.py, dwi_ml/tracking/projects/learn2track_propagator.py, dwi_ml/tracking/propagator.py, dwi_ml/tracking/tracker.py, dwi_ml/tracking/utils.py, scripts_python/l2t_track_from_model.py, scripts_python/tests/scripts_on_test_model/dwiml_track_from_model.py, scripts_python/tests/test_all_steps_learn2track.py
Moving stuff that will be common.
Preparing classes for multiple parenting.
=> Preparing field for transformers tracking

scripts_python/dwiml_visualize_logs.py
=> Choose log to plot. Plot many experiments together

dwi_ml/tracking/projects/learn2track_propagator.py, dwi_ml/tracking/propagator.py, dwi_ml/tracking/tracker.py, scripts_python/l2t_track_from_model.py
=> Fix tracking

bash_utilities/l2t_organize_from_tractoflow.sh, dwi_ml/models/main_models.py, dwi_ml/models/projects/learn2track_model.py, dwi_ml/models/projects/learn2track_utils.py, dwi_ml/models/projects/transforming_tractography.py, dwi_ml/tests/unit_tests/test_models_learn2track.py, dwi_ml/tests/unit_tests/test_models_transformers.py, dwi_ml/tests/utils/data_and_models_for_tests.py, dwi_ml/tracking/projects/learn2track_propagator.py, dwi_ml/tracking/propagator.py, dwi_ml/tracking/tracker.py, scripts_python/l2t_track_from_model.py, scripts_python/tests/scripts_on_test_model/dwiml_track_from_model.py, scripts_python/tto_track_from_model.py, scripts_python/tto_train_model.py, scripts_python/ttst_track_from_model.py, scripts_python/ttst_train_model.py
- Learn2track: During tracking (not training), wrong unpacking of sequences.
- Min, max length was verified with a "OR" instead of "AND"; was keeping everything
- Adding `normalize_output` option.
- Empty cache during tracking.
=> A few fixes for the tracking part

dwi_ml/data/processing/streamlines/data_augmentation.py, dwi_ml/data/spheres.py, dwi_ml/models/direction_getter_models.py, dwi_ml/models/main_models.py, dwi_ml/models/projects/learn2track_model.py, dwi_ml/tests/unit_tests/test_losses.py, dwi_ml/tests/unit_tests/test_models_and_trainer.py
- Fixing unpacking order during tracking for Learn2track
- Addition of noise (data augmentation in the batch sampler) was slow. Improving.
=> Small fixes and changes

dwi_ml/data/dataset/multi_subject_containers.py, dwi_ml/tracking/projects/learn2track_propagator.py, dwi_ml/tracking/propagator.py, dwi_ml/tracking/tracker.py, dwi_ml/tracking/utils.py, dwi_ml/training/trainers.py, scripts_python/l2t_track_from_model.py, scripts_python/tests/scripts_on_test_model/dwiml_track_from_model.py, scripts_python/tto_track_from_model.py, scripts_python/ttst_track_from_model.py
- Fix length verification at tracking time: accepting one more than max length because we add a final point at the end.
- Add no_grad context during tracking.
=> Fix: grad context (and more)

scripts_python/dwiml_compute_loss_copy_previous.py, scripts_python/tests/test_compute_loss_copy_previous.py
Debugging tool: script to print loss when keeping previous direction as output.
=> Add script to print loss when keeping previous direction

dwi_ml/models/direction_getter_models.py, dwi_ml/models/main_models.py, dwi_ml/models/projects/learn2track_model.py, dwi_ml/models/projects/learn2track_utils.py, dwi_ml/models/projects/transforming_tractography.py, dwi_ml/models/utils/direction_getters.py, dwi_ml/tests/unit_tests/test_models_learn2track.py, dwi_ml/tests/unit_tests/test_models_transformers.py, dwi_ml/tests/utils/data_and_models_for_tests.py, dwi_ml/tracking/propagator.py, scripts_python/dwiml_compute_loss_copy_previous.py, scripts_python/l2t_train_model.py, scripts_python/tests/test_compute_loss_copy_previous.py, scripts_python/tto_train_model.py, scripts_python/ttst_train_model.py
Easier management of options `--normalize_outputs` and `--normalize_targets`.
=> Change normalization param to float, move in direction getter

dwi_ml/data/hdf5/hdf5_creation.py, dwi_ml/data/hdf5/utils.py, dwi_ml/models/projects/learn2track_model.py, dwi_ml/tests/utils/data_and_models_for_tests.py, dwi_ml/tests/utils/expected_values.py, dwi_ml/tests/visual_tests/analyze_batch_loader_visually.py, dwi_ml/tests/visual_tests/visualise_error_sft.py, dwi_ml/training/batch_loaders.py, dwi_ml/training/utils/batch_loaders.py, dwi_ml/utils.py, scripts_python/dwiml_compute_loss_copy_previous.py, scripts_python/dwiml_visualize_copy_keep_prev_dir.py, scripts_python/l2t_visualize_error.py
Add scripts to visualize error (displacement) of next direction using trained models.
=> Visualize error

.github/workflows/test_package.yml, doc/getting_started.rst, dwi_ml/experiment_utils/tqdm_logging.py, dwi_ml/training/trainers.py, requirements.txt, requirements_github.txt, scripts_python/dwiml_visualize_logs.py, scripts_python/l2t_resume_training_from_checkpoint.py, scripts_python/l2t_train_model.py, scripts_python/tests/scripts_on_test_model/dwiml_train_model.py, scripts_python/tto_resume_training_from_checkpoint.py, scripts_python/tto_train_model.py, scripts_python/ttst_resume_training_from_checkpoint.py, scripts_python/ttst_train_model.py
Waiting for PR 662 in scilpy to be approved.
=> Upgrading to python 3.10

dwi_ml/data/hdf5/hdf5_creation.py
Module tractogram has changed in scilpy.
=> Follow latest changes scilpy

bash_utilities/scil_score_ismrm_Renauld2023.sh
=> Fix bbox in score_ismrm

dwi_ml/data/processing/streamlines/sos_eos_management.py, dwi_ml/data/spheres.py, dwi_ml/models/direction_getter_models.py, dwi_ml/models/main_models.py, dwi_ml/models/projects/learn2track_model.py, dwi_ml/models/projects/stacked_rnn.py, dwi_ml/models/projects/transforming_tractography.py, dwi_ml/tracking/projects/learn2track_tracker.py, dwi_ml/training/trainers.py, dwi_ml/training/utils/monitoring.py, dwi_ml/unit_tests/test_batch_sampler.py, dwi_ml/unit_tests/test_dataset.py, dwi_ml/unit_tests/test_losses.py, dwi_ml/unit_tests/test_models_learn2track.py
=> A few small fixes

dwi_ml/data/dataset/mri_data_containers.py, dwi_ml/data/dataset/multi_subject_containers.py, dwi_ml/models/projects/transforming_tractography.py, dwi_ml/testing/projects/copy_prev_dirs_tester.py, dwi_ml/testing/testers.py, dwi_ml/tracking/tracker.py, dwi_ml/unit_tests/test_dataset.py, dwi_ml/visu/visu_loss.py, scripts_python/dwiml_compute_loss_copy_previous.py, scripts_python/l2t_track_from_model.py, scripts_python/l2t_visualize_loss.py, scripts_python/tto_track_from_model.py, scripts_python/tto_visualize_loss.py, scripts_python/ttst_track_from_model.py, scripts_python/ttst_visualize_loss.py
=> Fix cache = Improve tracking time. Remove DataLoader.

dwi_ml/data/processing/utils.py, dwi_ml/models/main_models.py, dwi_ml/models/projects/copy_previous_dirs.py, dwi_ml/models/projects/learn2track_model.py, dwi_ml/models/projects/transforming_tractography.py, dwi_ml/testing/testers.py, dwi_ml/tracking/projects/learn2track_tracker.py, dwi_ml/training/batch_loaders.py, dwi_ml/training/batch_samplers.py, dwi_ml/training/projects/learn2track_trainer.py, dwi_ml/training/trainers.py, dwi_ml/training/utils/batch_loaders.py, dwi_ml/training/utils/monitoring.py, dwi_ml/unit_tests/test_batch_loader.py, dwi_ml/unit_tests/test_previous_dirs.py, dwi_ml/unit_tests/utils/data_and_models_for_tests.py, dwi_ml/unit_tests/visual_tests/analyze_batch_loader_visually.py, dwi_ml/unit_tests/visual_tests/visualise_error_sft.py, dwi_ml/visu/projects/transformer_visualisation_utils.py, scripts_python/dwiml_visualize_noise_on_streamlines.py
- Remove Gaussian noise variability
- Remove L2T hidden weights evolution memory for visu
and small fixes
=> Remove unuseful variable

dwi_ml/data/processing/streamlines/post_processing.py, dwi_ml/models/direction_getter_models.py
Not weighting loss on the last point when EOS is used.
=> Fix weight with angle with EOS.

dwi_ml/models/projects/learn2track_model.py, dwi_ml/models/projects/transformers_utils.py, dwi_ml/models/projects/transforming_tractography.py, dwi_ml/models/utils/direction_getters.py, scripts_python/l2t_train_model.py, scripts_python/tt_train_model.py
If dropout was given and not dg_dropout, dg_dropout was set to dropout. Removing these lines both in TT and L2T.
=> Remove_dg_dropout_default

dwi_ml/tracking/projects/utils.py, scripts_python/l2t_track_from_model.py, scripts_python/tt_track_from_model.py
+ Fix: use option in tt_track_model.
=> Rename option append_last like in scilpy

dwi_ml/data/processing/streamlines/post_processing.py, dwi_ml/models/direction_getter_models.py, dwi_ml/models/projects/learn2track_model.py, dwi_ml/models/utils/direction_getters.py, dwi_ml/testing/testers.py, dwi_ml/testing/visu_loss.py, dwi_ml/tracking/io_utils.py, dwi_ml/training/projects/learn2track_trainer.py, dwi_ml/training/projects/transformer_trainer.py, dwi_ml/training/trainers.py, dwi_ml/training/utils/batch_samplers.py, dwi_ml/training/utils/gradient_norm.py, dwi_ml/training/utils/monitoring.py, dwi_ml/training/with_generation/trainer.py, dwi_ml/unit_tests/test_submethods_losses.py, dwi_ml/unit_tests/test_train_trainerOneInput.py, dwi_ml/unit_tests/visual_tests/analyze_batch_loader_visually.py, scripts_python/dwiml_compute_loss_copy_previous.py, scripts_python/l2t_track_from_model.py, scripts_python/tests/test_all_steps_learn2track.py, scripts_python/tests/test_compute_loss_copy_previous.py, scripts_python/tt_track_from_model.py
Using Gaussians for the first time:
- Adding EOS (was a toDo)
- Fixing batch packing management.
- Adding comments and warning about stability of that model.
=> Finalize Gaussian model.

dwi_ml/data/dataset/multi_subject_containers.py, dwi_ml/data/processing/space/neighborhood.py, dwi_ml/models/main_models.py, dwi_ml/models/projects/learn2track_model.py, dwi_ml/models/projects/transformer_models.py, dwi_ml/training/batch_loaders.py, dwi_ml/training/trainers.py, dwi_ml/training/utils/monitoring.py, dwi_ml/training/utils/trainer.py, dwi_ml/unit_tests/utils/data_and_models_for_tests.py, dwi_ml/unit_tests/utils/expected_values.py, scripts_python/l2t_train_model.py, scripts_python/tests/test_all_steps_learn2track.py, scripts_python/tt_train_model.py
Removing all deprecated parameters' support.
Waiting for new test data to be added to scilpy's data fetcher.
=> Remove deprecated

.gitignore, dwi_ml/data/processing/dwi/dwi.py, dwi_ml/data/processing/streamlines/data_augmentation.py, dwi_ml/data/processing/streamlines/post_processing.py, dwi_ml/testing/projects/transformer_visualisation_utils.py, dwi_ml/tracking/io_utils.py, dwi_ml/tracking/tracker.py, requirements.txt
Back to the master scilpy.
Was required because the data fetcher has been updated as of yesterday. (Google drive has changed something.) Else, pytests won't work.
=> Back to master scilpy

dwi_ml/data/processing/space/neighborhood.py, dwi_ml/experiment_utils/prints.py, dwi_ml/models/direction_getter_models.py, dwi_ml/models/main_models.py, dwi_ml/models/projects/copy_previous_dirs.py, dwi_ml/models/projects/learn2track_model.py, dwi_ml/testing/projects/tt_visu_main.py, dwi_ml/testing/testers.py, dwi_ml/testing/visu_loss.py, dwi_ml/testing/visu_loss_utils.py, dwi_ml/training/batch_loaders.py, dwi_ml/training/batch_samplers.py, dwi_ml/training/trainers.py, dwi_ml/training/utils/monitoring.py, dwi_ml/unit_tests/test_directionGetter_losses.py, dwi_ml/unit_tests/test_submethods_losses.py, dwi_ml/unit_tests/utils/data_and_models_for_tests.py, dwi_ml/viz/logs_plots.py, scripts_python/dwiml_compute_loss_copy_previous.py, scripts_python/dwiml_visualize_logs.py, scripts_python/l2t_update_deprecated_exp.py, scripts_python/tests/test_all_steps_l2t.py, scripts_python/tests/test_all_steps_tto.py, scripts_python/tests/test_all_steps_tts.py, scripts_python/tests/test_all_steps_ttst.py, scripts_python/tests/test_compute_loss_copy_previous.py
Greatly improving visu_loss functions.
=> Visu: Finalize visu loss, histogram, EOS probs, EOS errors

dwi_ml/data/processing/streamlines/data_augmentation.py, dwi_ml/io_utils.py, dwi_ml/testing/projects/tt_visu_colored_sft.py, dwi_ml/testing/projects/tt_visu_submethods.py, dwi_ml/testing/projects/tt_visu_utils.py, dwi_ml/unit_tests/utils/data_and_models_for_tests.py, requirements.txt, scripts_python/dwiml_compute_loss_copy_previous.py, scripts_python/dwiml_create_hdf5_dataset.py, scripts_python/dwiml_visualize_noise_on_streamlines.py, scripts_python/l2t_track_from_model.py, scripts_python/l2t_train_model.py, scripts_python/tt_track_from_model.py, scripts_python/tt_train_model.py
Make necessary updates to use scilpy 2.0
=> Update to scilpy 2.0 and torch 2.2.0

bash_utilities/scil_score_ismrm_Renauld2023.sh, dwi_ml/io_utils.py, dwi_ml/models/projects/transformer_models.py, dwi_ml/models/projects/transformer_sublayers.py, dwi_ml/models/utils/transformers_from_torch.py, dwi_ml/testing/projects/tt_visu_argparser.py, dwi_ml/testing/visu_loss_utils.py, requirements.txt, scripts_python/dwiml_create_hdf5_dataset.py, scripts_python/dwiml_visualize_logs.py, scripts_python/dwiml_visualize_logs_correlation.py, scripts_python/l2t_resume_training_from_checkpoint.py, scripts_python/l2t_track_from_model.py, scripts_python/l2t_train_model.py, scripts_python/l2t_update_deprecated_exp.py, scripts_python/tt_resume_training_from_checkpoint.py, scripts_python/tt_track_from_model.py, scripts_python/tt_train_model.py
Updated Transformers using new torch code.
Tested: 100% the same values as before.
=> Update transformers and scores bash

dwi_ml/data/processing/volume/interpolation.py, dwi_ml/models/main_models.py, dwi_ml/tracking/tracking_mask.py, dwi_ml/training/batch_loaders.py
=> ENH: make cache clearing optional

bash_utilities/scil_score_ismrm_Renauld2023.sh, dwi_ml/data/dataset/streamline_containers.py, dwi_ml/unit_tests/test_dataset.py, scripts_python/dwiml_compute_connectivity_matrix_from_labels.py, scripts_python/dwiml_hdf5_extract_data.py, scripts_python/dwiml_hdf5_print_architecture.py, scripts_python/tests/test_print_hdf5_architecture.py
New script to extract hdf5 data (helps verify that everything is ok) + small fixes.
=> New script + small fixes
