dwi_ml/data/processing/dwi/TO_SEND_TO_SCILPY.py
dwi_ml/data/processing/dwi/dwi.py

Note. 
`from scilpy.reconst.raw_signal import compute_sh_coefficients`
Uses something from a PR in scilpy. We can wait for this to be accepted.
https://github.com/scilus/scilpy/pull/113

Preprocessing dwi

---

doc/requirements_doc.txt

Add missing `sphinx_rtd_theme` package to doc requirements file.
Required [here](https://github.com/scil-vital/dwi_ml/blob/master/doc/conf.py#L57).
Fixes
```
$ ~/src/dwi_ml(master)$ make -C . clean && make -C . html
make : on entre dans le répertoire
« /src/dwi_ml »
make : on quitte le répertoire « /src/dwi_ml »
make : on entre dans le répertoire « /src/dwi_ml »
Running Sphinx v1.7.4
making output directory...
loading pickled environment... not yet created
Theme error:
sphinx_rtd_theme is no longer a hard dependency since version 1.4.0. Please
install it manually.(pip install sphinx_rtd_theme)
Makefile:20 : la recette pour la cible « html » a échouée
make: *** [html] Erreur 2
make : on quitte le répertoire « /src/dwi_ml »
```

BUG: Add missing `sphinx_rtd_theme` package to doc requirements

---

utils/gitsetup/setup-hooks.sh
utils/hooks/commit-msg
utils/hooks/prepare-commit-msg

Add commit message-related pre-commit hooks:
- `utils/hooks/prepare-commit-msg` inserts a custom message in the commit
message comments showing the standard commit message subject prefixes.
- `utils/hooks/commit-msg` checks whether the commit message conforms to the
standard prefixes.
- `utils/gitsetup/setup-hooks.sh` sets up the hooks.

ENH: Add commit message-related pre-commit hooks

---

README.rst
doc/creating_hdf5.rst
doc/data_organization.rst
doc/devel/contributing_link.rst
doc/index.rst
doc/preprocessing.rst
doc/processing.rst
doc/reminder_tractoflow_output.rst

Here is the list of problems solved:
**- Some broken links :** Some double apostrophe :ref:`` oups`` should be changed to :ref:`aahh`. However, this works for the doc but not for the readme directly on github. Changing for reference as a link ( `link <to_this_link>`_), and also, removing all relative links (ex, ./here) to absolute links because github and the doc don't have the same root. Absolute links start with https://dwi-ml.readthedocs.io/en/latest/.
**- Making sure all pages are included :** some pages were not included in any toctree. 
- I added the page "processing" to regroup the future pages explaining everything similar to CreateHDF5, which was not included anywhere.
- The CONTRIBUTING page could not be included easily because it is outside the doc folder (as per a previous …

Repairing the doc

---

please_copy_and_adapt/organize_from_recobundles.sh
please_copy_and_adapt/organize_from_tractoflow.sh

--> The script did not work if the subject list was separated with spaces instead of newlines in $subjects_list. Changed the way to read the file. Tested, it now works in both cases.
--> We were printing information that checks were not done if all files existed for all subjects. I added these checks.
--> Improved the information in comments.
Here is how I tested on Béluga:
```
database_folder=./YOUR_PATH/hcp_1200/derivatives/
cp -as /home/USER/projects/rrg-descotea/datasets/hcp_1200/derivatives/tractoflow/output/results_ranByEmma/results/ $database_folder/processed
cd .$database_folder/processed
echo s* > subjects_list.txt
bash organize_from_tractoflow.sh $database_folder $subject_list
```
- [x ] Added a description of the content of this PR above
- [x ] Followed [proper commit message …

Improving organize_from_tractoflow and _from_recobundles

---

requirements.txt

I installed dwi_ml today on python 3.7. after installing scilpy.
Requirements in scilpy have changed so I am updating our's to fit!

Updated requirements to fit scilpy's

---

dwi_ml/model/direction_getter_models.py
dwi_ml/model/utils_for_fisher_von_mises.py
dwi_ml/model/utils_for_gaussians.py
requirements.txt
setup.py
tests/test_direction_getter_models.py

Philippe had done a good job last year of cleaning the "output models" but I reverified all the formulas, and added tests.
More important changes:
- I copied tests from Philippe's repo and added more for missing models (sphere class and fisher von mises)
- Gaussian mixture: name of variable was variance but base on formula, it really is sigma, the standard deviation +there was a wrong variable name used (self.layers_mixture, new line 471)
Other details:
- I moved computation of the log prob to utils to have more place for a complete doc and formulas, reviewed all formulas.
- Doc talked about the "100 points" of the sphere but it is actually 724.
- Modified some doc to fit pep8. Changed torch.tensor to tensor to save a lot of space.
- I noticed that torch is missing from requirements
- I …

STYLE: Reviewed output models + added tests

---

doc/creating_hdf5.rst
dwi_ml/data/dataset/data_lists.py
dwi_ml/data/dataset/multi_subject_containers.py
dwi_ml/data/dataset/single_subject_containers.py
dwi_ml/data/dataset/streamline_containers.py
dwi_ml/data/hdf5_creation.py
dwi_ml/model/batch_samplers.py
dwi_ml/training/checks_for_experiment_parameters.py
please_copy_and_adapt/config_file_example.json
please_copy_and_adapt/train_model.py
please_copy_and_adapt/training_parameters.yaml
scripts_python/create_hdf5_dataset.py
tests/running_tests.sh
tests/test_batch_sampler_iter.py
tests/test_multisubjectdataset_creation_from_hdf5.py

Changed the dataset creation to take the bundles name from the config_file, same as for the inputs. Also allowing more than one streamline group (ex, you could have your model use 'good examples' and 'bad examples' of streamlines). Changes are made in the multisubject containers, the batch sampler and the training.
All existing tests have been re-verified.

Allowing more than one streamline group

---

doc/data_containers.rst
doc/processing.rst
dwi_ml/data/dataset/multi_subject_containers.py
dwi_ml/data/dataset/single_subject_containers.py
dwi_ml/data/dataset/subjects_list_containers.py
dwi_ml/data/dataset/utils.py
dwi_ml/experiment/monitoring.py
dwi_ml/model/batch_samplers.py
dwi_ml/training/checks_for_experiment_parameters.py
dwi_ml/training/trainers.py
please_copy_and_adapt/train_model.py
please_copy_and_adapt/training_parameters.yaml
requirements.txt
tests/test_batch_sampler_iter.py
tests/test_batch_sampler_load_batch.py
tests/test_multisubjectdataset_creation_from_hdf5.py

There was a redondancy in the code when creating the dataset:
```
training_set = create_dataset(**params)
validation_set = create_dataset(**params)
```
meaning that the two datasets could have different parameters (ex, nb of features), which does not really makes sense in machine learning. So now they have been merged together in the multisubjectDataset, which will load data both for the training and validation set.
The batch samplers, however, are kept separated. We could indeed suppose that a user could want a different amount of noise addition during training and validation, for instance.
Doing this forced to change the hdf_handle management. But as of h5py2.4, the hdf5 file is now considered thread-safe so management could be alleged in dwi_ml.
All tests have been re-ran.

Merging training validation

---

dwi_ml/data/hdf5_creation.py
requirements.txt

- Fixed requirements
- Changed affine checks from array_equal to allclose because in one case for tractoinferno, affines were not equal due to numerical imprecision.

Fixes from running on tractoinferno

---

doc/config_file.rst
doc/creating_hdf5.rst
dwi_ml/data/hdf5_creation.py
dwi_ml/data/processing/dwi/dwi.py
please_copy_and_adapt/config_file_example.json
scripts_python/create_hdf5_dataset.py

- Allowing more than one mask: ex: we often have gm and wm masks. If we don't want to combine them in our dwi_ml folder, we can merge them directly in the hdf5.
- Standardization option now in the config file, so we can choose differently for each volume group. Ex: we can have a group in the hdf5 for masks, useful at tracking time (that we don't want to standardize)

Adding masks to hdf5

---

dwi_ml/data/dataset/multi_subject_containers.py
dwi_ml/data/dataset/utils.py
dwi_ml/data/processing/volume/interpolation.py
dwi_ml/models/main_models.py
dwi_ml/training/batch_loaders.py
dwi_ml/training/batch_samplers.py
dwi_ml/training/trainers.py
dwi_ml/training/utils/trainer.py
scripts_python/tests/t_batch_sampler_iter.py
scripts_python/tests/t_batch_sampler_load_batch.py
scripts_python/tests/t_multisubjectdataset_creation_from_hdf5.py

Now that we don't use yaml, defaults can safely be added back in class instantiation. 
Scripts has args for all variables anyway, but helps for faster testing, and removes pycharm warning in some cases when setting a variable to None.

Adding back defaults

---

dwi_ml/experiment_utils/tqdm_logging.py
dwi_ml/unit_tests/analyze_batch_loader_visually.py
dwi_ml/unit_tests/test_batch_loader.py
dwi_ml/unit_tests/test_batch_sampler.py
dwi_ml/unit_tests/test_dataset.py
dwi_ml/unit_tests/test_embeddings.py
dwi_ml/unit_tests/test_losses.py
dwi_ml/unit_tests/test_models_and_trainer.py
dwi_ml/unit_tests/test_models_learn2track.py
dwi_ml/unit_tests/test_models_transformers.py
dwi_ml/unit_tests/test_neighborhood.py
dwi_ml/unit_tests/test_packing.py
scripts_python/dwiml_create_hdf5_dataset.py
scripts_python/dwiml_visualize_logs.py
scripts_python/l2t_resume_training_from_checkpoint.py
scripts_python/l2t_track_from_model.py
scripts_python/l2t_train_model.py
scripts_python/tests/scripts_on_test_model/dwiml_resume_training_from_checkpoint.py
scripts_python/tests/scripts_on_test_model/dwiml_track_from_model.py
scripts_python/tto_resume_training_from_checkpoint.py
scripts_python/ttst_resume_training_from_checkpoint.py

Remove broken basicConfig usage. Depends too much on imported libraries. Ex: Dipy 1.5. breaks the basicConfig.

Remove basicConfig usage

---

dwi_ml/data/processing/dwi/dwi.py

With option 'independant', logging cannot print value; they are arrays, not values. Removing logging.

Fix independant norm

---

.github/workflows/test_package.yml
requirements.txt
requirements_github.txt

Latest official release should be ok for current uses.
Scilpy is about to change a lot, so for now, it's better to stop following the master branch.

Change Scilpy version

---

.github/workflows/test_package.yml
doc/getting_started.rst

It is an absolute mystery why previous tests worked for python 3.8. It does not locally. Scilpy does not support >3.7 right now.

Restrict tests to python 3.7

---

dwi_ml/data/processing/space/neighborhood.py
dwi_ml/data/processing/streamlines/post_processing.py
dwi_ml/data/processing/volume/interpolation.py
dwi_ml/models/direction_getter_models.py
dwi_ml/models/main_models.py
dwi_ml/models/projects/learn2track_model.py
dwi_ml/models/projects/transforming_tractography.py
dwi_ml/tests/unit_tests/test_models_and_trainer.py
dwi_ml/tests/unit_tests/test_models_transformers.py
dwi_ml/tests/unit_tests/test_neighborhood.py
dwi_ml/tests/utils/data_and_models_for_tests.py
dwi_ml/tracking/projects/learn2track_propagator.py
dwi_ml/tracking/projects/transformer_propagator.py
dwi_ml/tracking/propagator.py
dwi_ml/tracking/tracker.py
dwi_ml/tracking/utils.py
dwi_ml/training/batch_loaders.py
dwi_ml/training/trainers.py
scripts_python/l2t_track_from_model.py
scripts_python/tests/scripts_on_test_model/dwiml_track_from_model.py
scripts_python/tests/test_all_steps_learn2track.py
scripts_python/tests/test_all_steps_tto.py
scripts_python/tests/test_all_steps_ttst.py
scripts_python/tto_track_from_model.py
scripts_python/ttst_track_from_model.py

Trying to improve processing time. Using current tests, it does not seem to improve much. But it is now more logical, particularly for transformers: we don't move streamlines back and fourth between CPU and GPU at every propagation step.
Also, simplified propagator: Now we always send multiple streamlines.

Moving streamlines to torch

---

dwi_ml/data/dataset/mri_data_containers.py
dwi_ml/data/dataset/multi_subject_containers.py
dwi_ml/data/processing/space/neighborhood.py
dwi_ml/data/processing/streamlines/post_processing.py
dwi_ml/data/processing/volume/interpolation.py
dwi_ml/models/direction_getter_models.py
dwi_ml/models/main_models.py
dwi_ml/models/projects/learn2track_model.py
dwi_ml/models/projects/transforming_tractography.py
dwi_ml/models/utils/spheres.py
dwi_ml/tests/unit_tests/test_dataset.py
dwi_ml/tests/unit_tests/test_embeddings.py
dwi_ml/tests/unit_tests/test_models_learn2track.py
dwi_ml/tests/unit_tests/test_neighborhood.py
dwi_ml/tests/unit_tests/test_packing.py
dwi_ml/tests/unit_tests/test_previous_dirs.py
dwi_ml/tests/utils/data_and_models_for_tests.py
dwi_ml/tracking/projects/learn2track_propagator.py
dwi_ml/tracking/propagator.py
dwi_ml/tracking/tracker.py
dwi_ml/training/batch_loaders.py
dwi_ml/training/trainers.py
scripts_python/tests/scripts_on_test_model/test_all_steps_general.py
scripts_python/tests/test_all_steps_learn2track.py
scripts_python/tests/test_all_steps_tto.py
scripts_python/tests/test_all_steps_ttst.py

Finishing device management.
- Remove all unnecessary .to() when tensor could be created directly on the right device.
- Remove deprecated torch.Tensor() method.
- Remove torch.tensor(t) method: we should prefer torch.as_tensor() which does not copy the data.
- Add GPU tests to script tests.
- Add non_blocking when possible.

Fix device

---

dwi_ml/training/trainers.py

In the case where we stop the training mid-training, the local logs are not saved. Moved saving inside the loop.

Save logs locally every epoch

---

dwi_ml/experiment_utils/tqdm_logging.py
requirements.txt

Remove the `future` package dependency: it is no longer required in Python 3, and it is redundant.
Fixes the dependabot security warnings that are being raised weekly.
Documentation:
https://docs.python.org/3/reference/simple_stmts.html#future-statements

ENH: Remove `future` package dependency

---

dwi_ml/training/projects/trainers_for_generation.py
dwi_ml/training/trainers.py

Reusing the same validation batch instead of a whole new one. Avoids running more RNG seeds in the batch sampler to make sure models are the same with or without generation phase.

Generation validation: use same batch for better comparison between models

---

dwi_ml/models/projects/learn2track_model.py

Fix unpacking order of hidden state when preparing backward tracking.

L2T_fix_unpacking_hidden_state

---

requirements.txt
source/.readthedocs.yaml
source/README_how_to_setup_rtd.txt
source/docs_requirements.txt

Doc management is deprecated. Doc not building since one month.
Trying to set the migration details. Need to merge in order to see if worked.

Try to migrate to yaml

---

dwi_ml/models/main_models.py
dwi_ml/models/projects/learn2track_model.py
dwi_ml/models/projects/transformer_models.py
dwi_ml/tracking/tracker.py
dwi_ml/training/trainers.py
dwi_ml/training/with_generation/trainer.py
dwi_ml/unit_tests/utils/data_and_models_for_tests.py

Now always sending streamlines both in forward and in loss. Much simpler, not heavier. User can decide to ignore.

Removing unnecessary params model_uses_forward and loss_uses_forward

---

.github/workflows/test_package.yml
dwi_ml/data/hdf5/hdf5_creation.py
dwi_ml/data/hdf5/utils.py
dwi_ml/data/processing/streamlines/data_augmentation.py
dwi_ml/io_utils.py
dwi_ml/models/main_models.py
dwi_ml/testing/testers.py
dwi_ml/training/batch_loaders.py
scripts_python/dwiml_create_hdf5_dataset.py
scripts_python/dwiml_visualize_noise_on_streamlines.py

Add resampling with nb points and skip check header compatible when only tractograms.

[ENH] Add resample nb points + dps

---

dwi_ml/data/dataset/streamline_containers.py
dwi_ml/data/hdf5/hdf5_creation.py
dwi_ml/data/hdf5/utils.py
dwi_ml/data/processing/streamlines/data_augmentation.py
dwi_ml/unit_tests/test_dataset.py
dwi_ml/unit_tests/utils/data_and_models_for_tests.py
scripts_python/dwiml_create_hdf5_dataset.py
scripts_python/tests/test_create_hdf5_dataset.py
source/2_A_creating_the_hdf5.rst
source/2_B_advanced_hdf5_organization.rst

Started adding tests
- Changed dps from an arg in the script (`--dps_keys`) to a line in the config file. This works.
- Copied the file `streamline_containers` from Jeremi's PR and started testing. Does not seem to work yet. Need to check the data shape. Work to be continued.

Dps management

---

dwi_ml/data/processing/streamlines/post_processing.py
requirements.txt

Installation as it was not possible on beluga anymore. All my branches "for_beluga" have been deleted.
Starting anew. Currently, it is possible to install version 2.2.0-rc1 on beluga, so starting from there. 
That's a ~2 years improvement on scilpy's version. Unit tests passing, I will try to do a test-retest with my stuff see if results are roughly the same.

Update to scilpy 2.2.0 rc1
